name: pci_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.1.5

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  cross_file: ^0.3.4+1
  csv: ^6.0.0
  cupertino_icons: ^1.0.8
  file_picker: ^8.0.0+1
  firebase_analytics: ^10.10.0
  firebase_core: ^2.28.0
  firebase_crashlytics: ^3.5.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_map_math: ^0.1.7
  gap: ^3.0.1
  geolocator: ^11.0.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.6.0
  http: ^1.2.1
  intl: ^0.19.0
  mime: ^1.0.5
  path: ^1.9.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  postgres: ^3.2.0
  provider: ^6.1.2
  sensors_plus: ^5.0.0
  share_plus: ^9.0.0
  sqflite: ^2.3.2
  web_socket_channel: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib\Assets\gyroscope.png
    - lib\Assets\speedometer.png
    - lib\Assets\location.png
    - lib\Assets\Roads\road_drrp.geojson