name: pciapp
description: "PCI App"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  collection: ^1.18.0
  cross_file: ^0.3.4+1
  csv: ^6.0.0
  firebase_analytics: ^11.4.1
  firebase_core: ^3.0.0
  firebase_crashlytics: ^4.3.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  geolocator: ^13.0.2
  get: ^4.6.6
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.6.0
  http: ^1.2.1
  intl: ^0.20.2
  location: ^8.0.0
  mime: ^2.0.0
  path: ^1.9.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  sensors_plus: ^6.0.1
  share_plus: ^10.0.0
  sqflite: ^2.3.2
  logger: ^2.5.0
  archive: ^3.6.1
  get_storage: ^2.1.1
  wakelock_plus: ^1.2.8
  connectivity_plus: ^6.1.0
  pdf: ^3.11.1
  printing: ^5.13.4
  flutter_markdown: ^0.7.4+3
  auto_size_text: ^3.0.0
  widgets_to_image: ^1.0.0
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  google_sign_in: ^6.2.2
  url_launcher: ^6.3.1
  file_picker: ^8.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib\Assets\Roads\road_drrp.geojson
    - lib\Assets\SensorImages\gyroscope.svg
    - lib\Assets\SensorImages\location.svg
    - lib\Assets\SensorImages\speed.svg
    - lib\Assets\delete.svg
    - lib\Assets\share.svg
    - lib\Assets\profile.svg
    - lib\Assets\settings.svg
    - lib\Assets\journey1.svg
    - lib\Assets\journey2.svg
    - lib\Assets\statistics.svg
    - lib\Assets\empty_file.svg
    - lib\Assets\roadType\pave-road.svg
    - lib\Assets\roadType\un-pave-road.svg
    - lib\Assets\roadType\pedestrian-walk.svg
    - lib\Assets\roadType\break.svg
    - lib\Assets\roadType\no_break.svg
    - lib\Assets\roadType\cross_drainage.svg 
    - lib\Assets\roadType\bridge.svg 
    - lib\Assets\roadType\wallL.svg 
    - lib\Assets\roadType\wallS.svg 
