name: pci_app
description: "PCI App"
publish_to: "none"
version: 1.2.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  collection: ^1.18.0
  cross_file: ^0.3.4+1
  csv: ^6.0.0
  firebase_analytics: ^11.0.0
  firebase_core: ^3.0.0
  firebase_crashlytics: ^4.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  flutter_dotenv: ^5.2.1
  gap: ^3.0.1
  geolocator: ^13.0.2
  get: ^4.6.6
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.6.0
  http: ^1.2.1
  intl: ^0.19.0
  location: ^7.0.0
  mime: ^2.0.0
  path: ^1.9.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  sensors_plus: ^6.0.1
  share_plus: ^10.0.0
  sqflite: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - lib\Assets\Roads\road_drrp.geojson
    - lib\Assets\SensorImages\gyroscope.svg
    - lib\Assets\SensorImages\location.svg
    - lib\Assets\SensorImages\speed.svg
    - lib\Assets\delete.svg
    - lib\Assets\profile.svg
    - lib\Assets\share.svg
    - lib\Assets\settings.svg
    - lib\Assets\past-trips.svg
    - lib\Assets\past_trips_selected.svg
    - lib\Assets\journey1.svg
    - lib\Assets\journey2.svg
    - lib\Assets\empty_file.svg
