name: pci_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  csv: ^6.0.0
  file_picker: ^8.0.0+1
  firebase_analytics: ^10.10.0
  firebase_core: ^2.28.0
  firebase_crashlytics: ^3.5.0
  flutter:
    sdk: flutter
  flutter_map_math: ^0.1.7
  gap: ^3.0.1
  geolocator: ^11.0.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.6.0
  http: ^1.2.1
  intl: ^0.19.0
  path: ^1.9.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  sensors_plus: ^5.0.0
  share_plus: ^8.0.2
  sqflite: ^2.3.2
  web_socket_channel: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib\Assets\gyroscope.png
    - lib\Assets\speedometer.png