// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-RaR-Yzx9CVHG8idBlzTApjyZychPSvw',
    appId: '1:94412646522:web:d9e40462edeab8780eb3c3',
    messagingSenderId: '94412646522',
    projectId: 'pci-app-6be73',
    authDomain: 'pci-app-6be73.firebaseapp.com',
    storageBucket: 'pci-app-6be73.appspot.com',
    measurementId: 'G-PTPRPJTRET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCof0Jiw77HWM_PlWG8n0_Yf2XrRzAsBk',
    appId: '1:94412646522:android:9269ed825d42a01e0eb3c3',
    messagingSenderId: '94412646522',
    projectId: 'pci-app-6be73',
    storageBucket: 'pci-app-6be73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe2zw8OwAgcu_CjOwH4rbpdFDPyMk4BfY',
    appId: '1:94412646522:ios:fe51e355a6022a9d0eb3c3',
    messagingSenderId: '94412646522',
    projectId: 'pci-app-6be73',
    storageBucket: 'pci-app-6be73.appspot.com',
    iosBundleId: 'com.example.pciApp',
  );
}
